# Generated by Django 3.2.4 on 2021-07-06 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipousuario',
            options={'ordering': ['idTipoUsuario'], 'verbose_name': 'tipo de usuario', 'verbose_name_plural': 'tipos de usuarios'},
        ),
    ]
