# Generated by Django 3.2.5 on 2021-07-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombreEmpleado', models.CharField(max_length=100, verbose_name='Nombre Empleado')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='empleados', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'ordering': ['idEmpleado'],
            },
        ),
    ]
